// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gcdabdhpmvyxyscdddhd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjZGFiZGhwbXZ5eHlzY2RkZGhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0OTIzMTMsImV4cCI6MjA4NzA2ODMxM30.N04QM8fBYocUgam-FYW3-1dU4r_WHRBrU9fC-Zbojkc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});